name: Build Lune Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Create keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storeFile=keystore.jks
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD}}
          EOF

      - name: Read versionName
        id: version
        run: |
          VERSION=$(grep versionName app/build.gradle.kts | head -1 | sed 's/.*"\(.*\)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Lune ${{ steps.version.outputs.version }}
          files: app/build/outputs/apk/release/*apk
